-- MANUFACTURER
CREATE TABLE MANUFACTURER (
    MFR_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    COUNTRY VARCHAR2(100) NOT NULL
);

-- DRUG CATEGORY
CREATE TABLE DRUG_CATEGORY (
    DRUG_CODE VARCHAR2(50) PRIMARY KEY,
    DESCRIPTION VARCHAR2(255),
    MFR_ID NUMBER,
    FOREIGN KEY (MFR_ID) REFERENCES MANUFACTURER(MFR_ID)
);

-- TIME PERIOD
CREATE TABLE TIME_PERIOD (
    DATE_ID DATE PRIMARY KEY,
    YEAR NUMBER,
    MONTH NUMBER,
    WEEKDAY VARCHAR2(20),
    HOUR NUMBER
);

-- DRUG DETAILS (1:1 with DRUG_CATEGORY)
CREATE TABLE DRUG_DETAILS (
    DRUG_CODE VARCHAR2(50) PRIMARY KEY,
    NOTES VARCHAR2(255),
    FDA_APPROVAL_DATE DATE,
    FOREIGN KEY (DRUG_CODE) REFERENCES DRUG_CATEGORY(DRUG_CODE)
);

-- DRUG RECALL (1:M)
CREATE TABLE DRUG_RECALL (
    DRUG_CODE VARCHAR2(50),
    RECALL_NO NUMBER,
    RECALL_DATE DATE,
    REASON VARCHAR2(255),
    NOTES VARCHAR2(255),
    PRIMARY KEY (DRUG_CODE, RECALL_NO),
    FOREIGN KEY (DRUG_CODE) REFERENCES DRUG_CATEGORY(DRUG_CODE)
);

-- SALES (associative table)
CREATE TABLE SALES (
    DRUG_CODE VARCHAR2(50),
    DATE_ID DATE,
    UNITS_SOLD NUMBER,
    PRIMARY KEY (DRUG_CODE, DATE_ID),
    FOREIGN KEY (DRUG_CODE) REFERENCES DRUG_CATEGORY(DRUG_CODE),
    FOREIGN KEY (DATE_ID) REFERENCES TIME_PERIOD(DATE_ID)
);